[Add] MainCategoryView, SubCategoryView, ProductView
wecode-bootcamp-korea/25-1st-WEKEA-backend pull request #5
Opened 2021-10-12 14:40 UTC by BnDC

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- GET 요청시 상품 목록 불러오기 기능 구현  

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. MainCategoryView
    - GET 요청시 main_categories 목록 불러오는 view 작성

2. CateogryListView
    - GET 요청시 모든 sub_categories에 대해 거기에 포함된 목록 불러오는 view 작성

3. ProductListView
   - GET 요청시 subcategory의 id를 받아 그에 해당하는 products 와 subcategory 정보 불러오는 view 작성

4. ProductView
   - GET 요청시 product 하나에 대한 상세 정보 불러오는 view 작성

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 무턱대고 만들기 보다 만들기 전부터 프론트 분들과 소통을 먼저 하고 만드는 과정에 수정을 줄여야 겠다는 생각을 했다 
- 프론트 엔드 분들에게 더 편하게 값을 전달할 수 있는 방법이 무엇인가에 대해서 고민해봐야 겠다.

<br />

## :: 기타 질문 및 특이 사항

2021-10-13 04:35 UTC, kyeongraekim requested changes
아래 내용 참고하셔서 수정해주세요!~

2021-10-13 04:35 UTC, kyeongraekim commented on product/views.py
> +        return JsonResponse({"sub_categories" : result}, status = 200)
보다 연산속도가 빠른 리스트 컴프리헨션을 적용해서 코드를 업그레이드 해보세요!~

2021-10-13 04:35 UTC, kyeongraekim commented on product/views.py
> +            result['size'] = list(products.get(id = result['id']).product_sizes.all().values('id', 'width','length','height'))
너무 많은 메소드 동작을 수행하도록 하는 코드처럼 보이네요.
 values() 와 list() 메소드를 안쓰고 코드를 풀어나간다면 어떻게 할 수 있을까요?

2021-10-13 04:35 UTC, kyeongraekim commented on product/views.py
> +        product_dict = product.values('id', 'foreign_name', 'korea_name', 'price', 'information', 'description')[0]
첫 객체를 [0]으로 하는 인덱싱 보다는 .first() 메소드를 사용하는 것을 권고 드립니다~

2021-10-13 05:40 UTC, BnDC commented on product/views.py
> +            result['size'] = list(products.get(id = result['id']).product_sizes.all().values('id', 'width','length','height'))
![image](https://user-images.githubusercontent.com/86050295/137073701-b4b91765-b09f-4009-8e61-dfa67048763d.png)

이런 수정을 말씀 하시는 걸까요??

2021-10-13 08:00 UTC, lordmyshepherd requested changes

2021-10-13 08:00 UTC, lordmyshepherd commented on product/views.py
> +        product_dict['reviews'] = list(product.first().reviews.all().values())
1. filter보다는 get을 사용해 주세요. 이유는 자원 하나를 조회할 경우에는 코드를 읽는 입장에서 get이 더 명확합니다.
2. values + list 보다는 instance의 . notion으로 가져올 수 있도록 수정해주세요.

2021-10-14 01:26 UTC, lordmyshepherd commented on product/views.py
> +        sub_category_id = int(request.GET.get('subcategoryid', None))
snake case인 `subcategory_id`를 사용하던지 camel case인 `subcategoryId`를 사용하던지 둘 중에 하나로 수정해주세요.
```suggestion
        sub_category_id = int(request.GET.get('subcategoryId', None))
```

2021-10-14 01:27 UTC, lordmyshepherd commented on product/views.py
> +        print(sub_category_id)
프린트문은 지워주세요!
디버깅할 때 사용했던 코드는 반드시 지워서 올려주시고, push 하신 후에 올리신 코드를 꼭 다시 검토해주세요!

2021-10-14 01:32 UTC, lordmyshepherd commented on product/views.py
> +class RandomProductView(View):
RandomProductView랑 ProductListView랑 합쳐주세요!
(client에서 random으로 정렬할 것 인지 id 기준으로 정렬할 것 인지 조건을 받아서 구현해주세요.)

2021-10-14 02:11 UTC, BnDC commented on product/views.py
> +        sub_category_id = int(request.GET.get('subcategoryid', None))
URL에 들어갈 부분이락 대문자와 _를 쓰지 않게 되어 있는 것으로 알고 있는데
query parameter의 경우 상관없나요??

2021-10-14 02:13 UTC, BnDC commented on product/views.py
> +class RandomProductView(View):
넵 RandomProductView를 추천 제품 목록에 쓰려고 했는데 그냥 ProductListView 쓰기로 했습니다

2021-10-14 10:01 UTC, merged